### ISSUE TITLE
fix ci testing fails

### ISSUE THREAD

**Issue by billcoding** [go-the-way/exl#5]
# github.com/go-the-way/exl [github.com/go-the-way/exl.test]
./read.go:241: type declarations inside generic functions are not currently supported
FAIL    github.com/go-the-way/exl [build failed]
FAIL

Exited with code exit status 2

**Comment by billcoding** [comment]
@oliverkahrmann-basf Thanks for contributing.PLS fix this issue.

**Comment by oliverkahrmann-basf** [comment]
Sounds like a compatibility issue with go 1.18. I'll check, thank you for mentioning.
